"""
core/ticker_lists.py
Predefined ticker universes for batch backtesting.
"""

NIFTY50 = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BPCL.NS",
    "BHARTIARTL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS",
    "DRREDDY.NS", "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS",
    "HDFCLIFE.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS",
    "ITC.NS", "INDUSINDBK.NS", "INFY.NS", "JSWSTEEL.NS", "KOTAKBANK.NS",
    "LT.NS", "M&M.NS", "MARUTI.NS", "NTPC.NS", "NESTLEIND.NS",
    "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SHRIRAMFIN.NS",
    "SBIN.NS", "SUNPHARMA.NS", "TCS.NS", "TATACONSUM.NS", "TATAMOTORS.NS",
    "TATASTEEL.NS", "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS",
]

INDIA_ETFS = [
    "NIFTYBEES.NS", "GOLDBEES.NS", "JUNIORBEES.NS", "BANKBEES.NS",
    "ICICIB22.NS", "ITBEES.NS", "MON100.NS", "MAFANG.NS",
]

US_ETFS = [
    "SPY", "QQQ", "VTI", "VOO", "DIA", "IWM", "GLD", "ARKK",
]

TICKER_UNIVERSES = {
    "Nifty50": NIFTY50,
    "India ETFs": INDIA_ETFS,
    "US ETFs": US_ETFS,
}
